import argparse
import json
import os
from datetime import datetime

from osgeo import gdal, osr


def utc_now_iso():
    return datetime.utcnow().isoformat() + "Z"


def ensure_dir(path):
    os.makedirs(path, exist_ok=True)


def normalize_lon_lat(x, y):
    # Handle axis-order ambiguity from GDAL/OSR.
    if abs(x) <= 90 and abs(y) > 90:
        return y, x
    return x, y


def extract_target_from_tif(path):
    ds = gdal.Open(path)
    if ds is None:
        raise RuntimeError(f"Could not open TIFF: {path}")

    gt = ds.GetGeoTransform()
    prj = ds.GetProjectionRef()
    width = ds.RasterXSize
    height = ds.RasterYSize
    epsg = None

    srs_src = osr.SpatialReference()
    if prj:
        srs_src.ImportFromWkt(prj)
        epsg_text = srs_src.GetAttrValue("AUTHORITY", 1)
        if epsg_text is not None:
            try:
                epsg = int(epsg_text)
            except ValueError:
                epsg = None

    minx = gt[0]
    maxy = gt[3]
    maxx = minx + gt[1] * width
    miny = maxy + gt[5] * height

    bbox_native = [float(minx), float(miny), float(maxx), float(maxy)]

    srs_wgs84 = osr.SpatialReference()
    srs_wgs84.ImportFromEPSG(4326)
    transformer = osr.CoordinateTransformation(srs_src, srs_wgs84)

    ll = transformer.TransformPoint(minx, miny)
    ur = transformer.TransformPoint(maxx, maxy)
    lon1, lat1 = normalize_lon_lat(ll[0], ll[1])
    lon2, lat2 = normalize_lon_lat(ur[0], ur[1])
    bbox_wgs84 = [
        float(min(lon1, lon2)),
        float(min(lat1, lat2)),
        float(max(lon1, lon2)),
        float(max(lat1, lat2)),
    ]

    px_x = float(gt[1])
    px_y = float(gt[5])
    crs_name = f"EPSG:{epsg}" if epsg is not None else "EPSG:4326"

    basename = os.path.splitext(os.path.basename(path))[0]
    return {
        "name": basename,
        "source_path": os.path.abspath(path),
        "width": int(width),
        "height": int(height),
        "bands": int(ds.RasterCount),
        "dtype": gdal.GetDataTypeName(ds.GetRasterBand(1).DataType),
        "crs": crs_name,
        "epsg": epsg,
        "pixel_size": [px_x, px_y],
        "bbox_native": bbox_native,
        "bbox_wgs84": bbox_wgs84,
    }


def render_python_export_script(targets, args):
    target_json = json.dumps(targets, indent=2)
    return f"""# Auto-generated by tools/qa/build_gee_calibration_targets.py
import ee

TARGETS = {target_json}

def main():
    ee.Initialize(project={repr(args.project) if args.project else "None"})
    for t in TARGETS:
        lon_min, lat_min, lon_max, lat_max = t["bbox_wgs84"]
        region = ee.Geometry.Rectangle([lon_min, lat_min, lon_max, lat_max], proj="EPSG:4326", geodesic=False)

        col = (
            ee.ImageCollection("COPERNICUS/S2_SR_HARMONIZED")
            .filterBounds(region)
            .filterDate("{args.year}-01-01", "{args.year}-12-31")
            .filter(ee.Filter.lt("CLOUDY_PIXEL_PERCENTAGE", {args.cloud_max}))
            .select({args.bands})
        )
        img = col.median().clip(region)

        desc = f"calib_{{t['name']}}_{args.year}"
        task = ee.batch.Export.image.toDrive(
            image=img,
            description=desc,
            folder={repr(args.drive_folder)},
            fileNamePrefix=desc,
            region=region,
            crs=t["crs"],
            dimensions=f"{{t['width']}}x{{t['height']}}",
            fileFormat="GeoTIFF",
            maxPixels=1e13,
        )
        task.start()
        print("started", desc)

if __name__ == "__main__":
    main()
"""


def maybe_queue_exports(targets, args):
    import ee

    ee.Initialize(project=args.project if args.project else None)
    started = 0
    for t in targets:
        lon_min, lat_min, lon_max, lat_max = t["bbox_wgs84"]
        region = ee.Geometry.Rectangle([lon_min, lat_min, lon_max, lat_max], proj="EPSG:4326", geodesic=False)

        col = (
            ee.ImageCollection("COPERNICUS/S2_SR_HARMONIZED")
            .filterBounds(region)
            .filterDate(f"{args.year}-01-01", f"{args.year}-12-31")
            .filter(ee.Filter.lt("CLOUDY_PIXEL_PERCENTAGE", args.cloud_max))
            .select(args.bands)
        )
        img = col.median().clip(region)

        desc = f"calib_{t['name']}_{args.year}"
        task = ee.batch.Export.image.toDrive(
            image=img,
            description=desc,
            folder=args.drive_folder,
            fileNamePrefix=desc,
            region=region,
            crs=t["crs"],
            dimensions=f"{t['width']}x{t['height']}",
            fileFormat="GeoTIFF",
            maxPixels=1e13,
        )
        task.start()
        started += 1
        print(f"[{utc_now_iso()}] started task: {desc}")
    return started


def main():
    parser = argparse.ArgumentParser(
        description="Build calibration targets from sample TIFF footprints and optionally start GEE exports"
    )
    parser.add_argument(
        "--samples",
        nargs="+",
        default=[
            r"C:\Users\ermil\Downloads\sample_1.tif",
            r"C:\Users\ermil\Downloads\sample_2.tif",
            r"C:\Users\ermil\Downloads\sample_3.tif",
        ],
        help="Sample GeoTIFF paths used as calibration footprints",
    )
    parser.add_argument("--year", type=int, default=2021, help="Sentinel-2 year")
    parser.add_argument("--cloud-max", type=float, default=30.0, help="Max CLOUDY_PIXEL_PERCENTAGE")
    parser.add_argument("--bands", nargs="+", default=["B4", "B3", "B2", "B8"], help="Sentinel-2 bands")
    parser.add_argument("--drive-folder", default="CPI_Calibration", help="Google Drive folder for exports")
    parser.add_argument("--project", default="", help="Optional Earth Engine project id")
    parser.add_argument(
        "--targets-json",
        default="calibration_targets.json",
        help="Output JSON path for extracted targets",
    )
    parser.add_argument(
        "--gee-script",
        default="tools/qa/generated_calibration_gee_export.py",
        help="Output path for generated standalone GEE export script",
    )
    parser.add_argument(
        "--queue-exports",
        action="store_true",
        help="Immediately queue GEE Drive export tasks (requires ee auth)",
    )
    args = parser.parse_args()

    targets = []
    for sample in args.samples:
        if not os.path.exists(sample):
            raise FileNotFoundError(f"Sample not found: {sample}")
        t = extract_target_from_tif(sample)
        targets.append(t)
        print(
            f"[{utc_now_iso()}] target={t['name']} crs={t['crs']} "
            f"size={t['width']}x{t['height']} bbox_wgs84={t['bbox_wgs84']}"
        )

    ensure_dir(os.path.dirname(args.targets_json) or ".")
    payload = {
        "generated_at": utc_now_iso(),
        "year": args.year,
        "cloud_max": args.cloud_max,
        "bands": args.bands,
        "drive_folder": args.drive_folder,
        "targets": targets,
    }
    with open(args.targets_json, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)
    print(f"[{utc_now_iso()}] wrote targets JSON: {args.targets_json}")

    script_body = render_python_export_script(targets, args)
    ensure_dir(os.path.dirname(args.gee_script) or ".")
    with open(args.gee_script, "w", encoding="utf-8") as f:
        f.write(script_body)
    print(f"[{utc_now_iso()}] wrote GEE export script: {args.gee_script}")

    if args.queue_exports:
        started = maybe_queue_exports(targets, args)
        print(f"[{utc_now_iso()}] queued {started} export tasks")


if __name__ == "__main__":
    main()
