# Auto-generated by tools/qa/build_gee_calibration_targets.py
import ee

TARGETS = [
  {
    "name": "sample_1",
    "source_path": "C:\\Users\\ermil\\Downloads\\sample_1.tif",
    "width": 1000,
    "height": 600,
    "bands": 4,
    "dtype": "Byte",
    "crs": "EPSG:32634",
    "epsg": 32634,
    "pixel_size": [
      10.0,
      -10.0
    ],
    "bbox_native": [
      345000.0,
      5014000.0,
      355000.0,
      5020000.0
    ],
    "bbox_wgs84": [
      45.26240872563475,
      19.024334900820993,
      45.31852271885698,
      19.149973539444062
    ]
  },
  {
    "name": "sample_2",
    "source_path": "C:\\Users\\ermil\\Downloads\\sample_2.tif",
    "width": 1000,
    "height": 600,
    "bands": 4,
    "dtype": "Byte",
    "crs": "EPSG:32629",
    "epsg": 32629,
    "pixel_size": [
      10.0,
      -10.0
    ],
    "bbox_native": [
      600000.0,
      3544000.0,
      610000.0,
      3550000.0
    ],
    "bbox_wgs84": [
      32.027734530104695,
      -7.941006342054773,
      32.08092526338306,
      -7.834438913725741
    ]
  },
  {
    "name": "sample_3",
    "source_path": "C:\\Users\\ermil\\Downloads\\sample_3.tif",
    "width": 1000,
    "height": 600,
    "bands": 4,
    "dtype": "Byte",
    "crs": "EPSG:32614",
    "epsg": 32614,
    "pixel_size": [
      10.0,
      -10.0
    ],
    "bbox_native": [
      526980.0,
      4704000.0,
      536980.0,
      4710000.0
    ],
    "bbox_wgs84": [
      -98.67170439919283,
      42.48788448387954,
      -98.54963865552656,
      42.54150482838207
    ]
  }
]

def main():
    ee.Initialize(project=None)
    for t in TARGETS:
        lon_min, lat_min, lon_max, lat_max = t["bbox_wgs84"]
        region = ee.Geometry.Rectangle([lon_min, lat_min, lon_max, lat_max], proj="EPSG:4326", geodesic=False)

        col = (
            ee.ImageCollection("COPERNICUS/S2_SR_HARMONIZED")
            .filterBounds(region)
            .filterDate("2021-01-01", "2021-12-31")
            .filter(ee.Filter.lt("CLOUDY_PIXEL_PERCENTAGE", 30.0))
            .select(['B4', 'B3', 'B2', 'B8'])
        )
        img = col.median().clip(region)

        desc = f"calib_{t['name']}_2021"
        task = ee.batch.Export.image.toDrive(
            image=img,
            description=desc,
            folder='CPI_Calibration',
            fileNamePrefix=desc,
            region=region,
            crs=t["crs"],
            dimensions=f"{t['width']}x{t['height']}",
            fileFormat="GeoTIFF",
            maxPixels=1e13,
        )
        task.start()
        print("started", desc)

if __name__ == "__main__":
    main()
