ssa_countries:
  - Angola
  - Benin
  - Botswana
  - Burkina Faso
  - Burundi
  - Cabo Verde
  - Cape Verde
  - Cameroon
  - Central African Republic
  - Chad
  - Comoros
  - Congo
  - Republic of the Congo
  - Democratic Republic of the Congo
  - Dem. Rep. Congo
  - Cote d'Ivoire
  - Côte d'Ivoire
  - Djibouti
  - Equatorial Guinea
  - Eritrea
  - Eswatini
  - Swaziland
  - Ethiopia
  - Gabon
  - Gambia
  - The Gambia
  - Ghana
  - Guinea
  - Guinea-Bissau
  - Kenya
  - Lesotho
  - Liberia
  - Madagascar
  - Malawi
  - Mali
  - Mauritania
  - Mauritius
  - Mozambique
  - Namibia
  - Niger
  - Nigeria
  - Rwanda
  - Sao Tome and Principe
  - Senegal
  - Seychelles
  - Sierra Leone
  - Somalia
  - South Africa
  - South Sudan
  - S. Sudan
  - Sudan
  - Tanzania
  - United Republic of Tanzania
  - Togo
  - Uganda
  - Zambia
  - Zimbabwe

